let Gold     = (0.8 0.498039 0.196078)
let Copper   = (0.72 0.45 0.20)
let Bronze   = (0.55 0.47 0.14)
let Silver   = (0.90 0.91 0.98)
let Black    = (0 0 0)
let White    = (1 1 1)
let DarkGray = (0.025 0.025 0.025)
let SkyBlue  = (0.2422812 0.61720675 0.8307701) // From_sRGB(135 206 235)

Material
{
  name: "Floor0"
  metalness: 0
  roughness: 0.8
  diffuse: (0.3 0.3 0.3)
  specular: (0.1 0.1 0.1)
}

Material
{
  name: "Glass"
  metalness: 0
  roughness: 0.2
  diffuse: (0.04 0.10 0.04)
  specular: (0.4 0.4 0.4)
  transparency: (0.9 0.9 0.9)
  refractive_index: 1.55
}

Surface { name: "teacup"    file: "../bezier/teacup" }
Surface { name: "teapot"    file: "../bezier/teapot" }
Surface { name: "teaspoon"  file: "../bezier/teaspoon" }
Surface { name: "longwave"  file: "../bezier/longwave" }

Scene
{
    objects:
    [
    {
      name: "Floor"
      transform:
      {
        position: (0 0.2 0)
        scale: (20 0.4 20)
      }
      surface: { model: Get("longwave") }
      material: "Floor0"
    }
    {
      name: "Lights"
      objects:
      [
        {
          name: "The Light"
          transform:
          {
            position: (-10 5 +5)
          }
          light:
          {
            type: "point"
            color: *(3.1 White)
          }
        }
      ]
    }
    ]
}
